# Generated by Django 2.1.7 on 2019-02-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testCom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teste01', models.FloatField()),
                ('Teste02', models.FloatField()),
            ],
            options={
                'db_table': 'Teste2',
            },
        ),
    ]
