# Generated by Django 2.1.7 on 2019-02-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testCom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcom',
            name='TimeStamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
