# Generated by Django 2.1.7 on 2019-02-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testCom', '0002_testcom_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcom',
            name='Teste01',
            field=models.FloatField(db_column='Teste01'),
        ),
        migrations.AlterField(
            model_name='testcom',
            name='Teste02',
            field=models.FloatField(db_column='Teste02'),
        ),
        migrations.AlterField(
            model_name='testcom',
            name='TimeStamp',
            field=models.DateTimeField(blank=True, db_column='TimeStamp', null=True),
        ),
    ]
