# Generated by Django 2.1.7 on 2019-02-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testCom', '0004_auto_20190225_1200'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testcom',
            table='[dbo].[Teste2]',
        ),
    ]
