# Generated by Django 2.1.7 on 2019-02-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testCom', '0005_auto_20190225_1203'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testcom',
            table='[Teste].[dbo].[Teste2]',
        ),
    ]
