# Generated by Django 2.1.7 on 2019-02-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testCom', '0006_auto_20190225_1205'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testcom',
            table='[dbo].[Teste2]',
        ),
    ]
