# Generated by Django 2.1.7 on 2019-02-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testCom', '0009_auto_20190225_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcom',
            name='id',
        ),
        migrations.AlterField(
            model_name='testcom',
            name='TimeStamp',
            field=models.DateTimeField(db_column='TimeStamp', primary_key=True, serialize=False),
        ),
    ]
