# Generated by Django 2.1.7 on 2019-02-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hist_trafoa',
            name='CorrenteA',
            field=models.FloatField(),
        ),
        migrations.AlterModelTable(
            name='hist_trafoa',
            table='[GrandeRio].[dbo].[hist_TrafoA]',
        ),
    ]
