# Generated by Django 2.1.7 on 2019-02-20 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consulta', '0002_auto_20190220_0022'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hist_trafoa',
            table='hist_TrafoA',
        ),
    ]
