# Generated by Django 2.1.7 on 2019-02-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consulta', '0003_auto_20190220_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hist_trafoa',
            name='id',
        ),
        migrations.AlterField(
            model_name='hist_trafoa',
            name='CorrenteA',
            field=models.FloatField(db_column='CorrenteA'),
        ),
        migrations.AlterField(
            model_name='hist_trafoa',
            name='E3TimeStamp',
            field=models.DateTimeField(db_column='E3TimeStamp', primary_key=True, serialize=False),
        ),
    ]
