# Generated by Django 2.1.7 on 2019-02-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consulta', '0004_auto_20190225_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hist_trafoa',
            name='CorrenteA',
        ),
        migrations.AddField(
            model_name='hist_trafoa',
            name='Consumo',
            field=models.FloatField(blank=True, db_column='Consumo', null=True),
        ),
    ]
