# Generated by Django 2.1.7 on 2019-02-25 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consulta', '0006_auto_20190225_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hist_trafoa',
            name='DataFim',
        ),
        migrations.RemoveField(
            model_name='hist_trafoa',
            name='dataInicio',
        ),
    ]
